name: base
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.10.11=h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - conda=22.11.1=py310h06a4308_4
  - conda-content-trust=0.1.3=py310h06a4308_0
  - conda-package-handling=1.9.0=py310h5eee18b_1
  - cryptography=38.0.1=py310h9ce1e76_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py310h06a4308_0
  - pluggy=1.0.0=py310h06a4308_1
  - pycosat=0.6.4=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.8=h7a1cb2a_1
  - readline=8.2=h5eee18b_0
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py310h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - alembic==1.13.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - automat==24.8.1
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blinker==1.7.0
      - buildtools==1.0.6
      - causal-conv1d==1.1.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - comm==0.2.2
      - constantly==23.10.4
      - contourpy==1.2.0
      - cycler==0.12.1
      - databricks-cli==0.18.0
      - datasets==2.15.0
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.7
      - docker==6.1.3
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - einops==0.7.0
      - entrypoints==0.4
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.13.1
      - flask==3.0.0
      - fonttools==4.46.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - furl==2.1.3
      - gitdb==4.0.11
      - gitpython==3.1.40
      - greenlet==3.0.2
      - grpcio==1.64.1
      - gunicorn==21.2.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.19.4
      - hyperlink==21.0.0
      - idna==3.6
      - importlib-metadata==7.0.0
      - incremental==24.7.2
      - ipykernel==6.29.4
      - ipython==8.25.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.2
      - jupyterlab-language-pack-zh-cn==4.2.post1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - mako==1.3.0
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mlflow==2.9.1
      - mmcv==1.3.8
      - mmsegmentation==0.14.1
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - notebook-shim==0.2.4
      - numpy==1.26.2
      - oauthlib==3.2.2
      - opencv-python==4.8.1.78
      - orderedmultidict==1.0.1
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.1.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.1.0
      - platformdirs==4.1.0
      - prettytable==3.9.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==4.25.1
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==14.0.1
      - pyarrow-hotfix==0.6
      - pygments==2.18.0
      - pyjwt==2.8.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-hostlist==1.23.0
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - querystring-parser==1.2.4
      - redo==3.0.0
      - referencing==0.35.1
      - regex==2023.10.3
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.2
      - selective-scan==0.0.2
      - send2trash==1.8.3
      - sentry-sdk==2.14.0
      - setproctitle==1.3.3
      - setuptools==75.5.0
      - simplejson==3.19.3
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.23
      - sqlparse==0.4.4
      - stack-data==0.6.3
      - supervisor==4.2.5
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - thop==0.1.1-2209072238
      - threadpoolctl==3.2.0
      - timm==0.4.12
      - tinycss2==1.3.0
      - tokenizers==0.15.0
      - tomli==2.0.1
      - torch==2.1.2+cu118
      - torchvision==0.16.2+cu118
      - tornado==6.4.1
      - tqdm==4.66.1
      - traitlets==5.14.3
      - transformers==4.35.2
      - triton==2.1.0
      - twisted==24.10.0
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - ultralytics==8.3.31
      - ultralytics-thop==2.0.11
      - uri-template==1.3.0
      - urllib3==2.1.0
      - wcwidth==0.2.12
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.11
      - xxhash==3.4.1
      - yapf==0.40.2
      - yarl==1.9.4
      - zipp==3.17.0
      - zope-interface==7.1.1
prefix: /root/miniconda3
